voila/rna_voila/view/views.py
from operator import itemgetter
from urllib.parse import urlencode

from flask import jsonify, redirect, url_for, session, render_template, request, abort
from waitress import serve

from rna_voila import constants
from rna_voila.api.view_matrix import ViewMatrix
from rna_voila.api.view_splice_graph import ViewSpliceGraph
from rna_voila.config import ViewConfig
from rna_voila.exceptions import UnknownAnalysisType
from rna_voila.index import Index
from rna_voila.voila_log import voila_log
import os, sys
from flask import Blueprint, Flask
from flask_session import Session
import tempfile, atexit, shutil
from rna_voila.view.ucsc_api import make_custom_track
import traceback


if os.name != 'nt':
    import gunicorn.app.base
    from gunicorn.six import iteritems

    class GunicornStandaloneApplication(gunicorn.app.base.BaseApplication):

        def __init__(self, app, options=None):
            self.options = options or {}
            self.application = app
            super(GunicornStandaloneApplication, self).__init__()

        def load_config(self):
            config = dict([(key, value) for key, value in iteritems(self.options)
                           if key in self.cfg.settings and value is not None])
            for key, value in iteritems(config):
                self.cfg.set(key.lower(), value)

        def load(self):
            return self.application

def get_bp(name):

    env_confs = {}

    # for pyinstaller
    if getattr(sys, 'frozen', False):
        env_confs['template_folder'] = os.path.join(os.path.dirname(sys.executable), '_internal', 'voila', 'templates')
        env_confs['static_folder'] = os.path.join(os.path.dirname(sys.executable), '_internal', 'voila', 'static')

    if os.environ.get('VOILA_EXT_STATIC_FOLDER', None):
        env_confs['static_folder'] = os.environ['VOILA_EXT_STATIC_FOLDER']
    if os.environ.get('VOILA_EXT_STATIC_URL_PATH', None):
        env_confs['static_url_path'] = os.environ['VOILA_EXT_STATIC_URL_PATH']

    app = Flask(name, **env_confs)
    app.secret_key = os.urandom(16)
    app.config['EXT_URL_PREFIX'] = os.environ.get('VOILA_EXT_URL_PREFIX', '')
    app.config['SESSION_TYPE'] = 'filesystem'
    session_dir = tempfile.mkdtemp()
    app.config['SESSION_FILE_DIR'] = session_dir

    # we use blueprint to allow specifying the url_prefix for installation under uncooperative web server admins
    # this does not seem to be supported using the base app routes

    bp = Blueprint('main', name, url_prefix=app.config['EXT_URL_PREFIX'])

    # this runs in shutdown
    def close_running_threads():
        try:
            shutil.rmtree(session_dir)
        except:
            pass

    atexit.register(close_running_threads)
    Session(app)

    return app, bp


from rna_voila.view import deltapsi, heterogen, psi, splicegraph, multipsi


def run_service():
    port = ViewConfig().port
    host = ViewConfig().host
    run_app = get_app()

    # pass general app config to templates
    run_app.config['VOILA_CONFIG'] = ViewConfig()

    web_server = ViewConfig().web_server


    if ViewConfig().enable_passcode:
        voila_log().info(f'Passcode access: http://{host}:{port}/{ViewConfig().enable_passcode}')


    if web_server == 'waitress':
        serve(run_app, port=port, host=host, expose_tracebacks=ViewConfig().debug)
    elif web_server == 'gunicorn':
        if os.name == 'nt':
            raise Exception("Gunicorn is unsupported on windows")
        options = {
            'bind': '%s:%s' % (host, port),
            'workers': ViewConfig().num_web_workers,
            'timeout': 9999999
        }
        GunicornStandaloneApplication(run_app, options).run()
    elif web_server == 'flask':
        run_app.run(host=host, port=port, debug=True)
    else:
        raise Exception("Unsupported web server %s specified" % web_server)


def get_app():
    Index()
    analysis_type = ViewConfig().analysis_type
    if not ViewConfig().splice_graph_only and ViewConfig().long_read_file and analysis_type != constants.ANALYSIS_PSI:
        voila_log().critical("It is currently not supported to use long-read inputs with analysis other than PSI")
        sys.exit(-1)


    if not analysis_type:
        run_app = splicegraph.app

    elif analysis_type == constants.ANALYSIS_PSI:
        if len(ViewConfig().voila_files) > 1:
            run_app = multipsi.app
        else:
            run_app = psi.app

    elif analysis_type == constants.ANALYSIS_DELTAPSI:
        run_app = deltapsi.app

    elif analysis_type == constants.ANALYSIS_HETEROGEN:
        run_app = heterogen.app

    else:
        raise UnknownAnalysisType(analysis_type)

    if ViewConfig().enable_passcode:
        @run_app.before_request
        def password_check():
            if request.path.endswith(ViewConfig().enable_passcode):
                # url has correct passcode, set session
                session[ViewConfig().enable_passcode] = True
                return redirect(url_for('main.index'))
            elif not ViewConfig().enable_passcode in session:
                # the correct passcode is not in session either, deny access
                return abort(403)

    if not ViewConfig().ignore_inconsistent_group_errors and not ViewConfig().splice_graph_only:
        m_all = ViewMatrix()
        warnings = m_all.check_group_consistency()
        @run_app.before_request
        def group_consistancy_check():
            if warnings and not 'warnings' in session:
                session['warnings'] = []
                for warning in warnings:
                    session['warnings'].append(f'Warning: detected groups with the same name "{warning[0]}", which have different sets of experiments: {warning[1]}')


    return run_app


def copy_lsv(lsv_id, view_matrix, voila_file=None):
    with ViewSpliceGraph() as sg, view_matrix(voila_file=voila_file) as m:
        lsv = m.lsv(lsv_id)
        gene_id = lsv.gene_id
        gene = sg.gene(gene_id)
        lsv_junctions = lsv.junctions.tolist()
        lsv_exons = sg.lsv_exons(gene_id, lsv_junctions)

        juncs = list(j for j in sg.junctions(gene_id) if [j['start'], j['end']] in lsv_junctions)
        exons = list(e for e in sg.exons(gene_id) if (e['start'], e['end']) in lsv_exons)

        lsv_type = lsv.lsv_type
        strand, chromosome, name = itemgetter('strand', 'chromosome', 'name')(gene)
        genome = sg.genome

        if request.get_json():
            sample_name = request.get_json().get('group_name', None)
            sample_names = [sample_name]
        else:
            sample_names = m.group_names

        group_bins = dict(lsv.group_bins)
        bins = [group_bins[sample_name] for sample_name in sample_names]

        splice_graphs = []

        for exp_names in m.experiment_names:
            junc_dict = {
                'junctions': [],
                'exons': exons
            }
            for junc in juncs:
                junc = junc.copy()
                junction_reads = list(sg.junction_reads_exp(junc, exp_names))
                reads = sum(r['reads'] for r in junction_reads)
                junc['reads'] = reads
                junc_dict['junctions'].append(junc)

            splice_graphs.append(junc_dict)

    return jsonify({
        'sample_names': sample_names,
        'genome': genome,
        'lsv_text_version': constants.LSV_TEXT_VERSION,
        'splice_graphs': splice_graphs,
        'lsv': {
            'exons': exons,
            'junctions': juncs,
            'lsv_type': lsv_type,
            'strand': strand,
            'chromosome': chromosome,
            'lsv_id': lsv_id,
            'name': name,
            'bins': bins
        }
    })


def ucsc_href(genome, chromosome, start, end):
    query_string = {
        'db': genome,
        'position': chromosome + ':' + str(start) + '-' + str(end)
    }

    return 'http://genome.ucsc.edu/cgi-bin/hgTracks?' + urlencode(query_string)


def lsv_boundries(lsv_exons):
    if not lsv_exons:
        print("Warning: Empty LSV?")
        return -1, -1
    lsv_exons = list(e if e[1] != -1 else (e[0], e[0] + 10) for e in lsv_exons)
    lsv_exons = list(e if e[0] != -1 else (e[1] - 10, e[1]) for e in lsv_exons)
    start = max(e for es in lsv_exons for e in es if e != -1)
    end = min(e for es in lsv_exons for e in es if e != -1)
    return start, end


def gene_view(summary_template, gene_id, view_matrix, **kwargs):

    with ViewSpliceGraph() as sg:
        gene = sg.gene(gene_id)

        # For this gene, remove any already selected highlight/weighted lsvs from session.
        highlight = session.get('highlight', {})
        lsv_ids = [h for h in highlight if h.startswith(gene_id)]
        for lsv_id in lsv_ids:
            del highlight[lsv_id]
        session['highlight'] = highlight

        exons = list(sg.exons(gene_id))
        if not exons:
            return redirect(url_for('main.index'))
        start = min(e['start'] for e in exons if e['start'] != -1)
        end = max(e['end'] for e in exons if e['end'] != -1)
        href = ucsc_href(sg.genome, gene['chromosome'], start, end)

        gene.update({
            'start': start,
            'end': end,
            'href': href,
            'overlap': sg.gene_overlap(gene_id)
        })

        kwargs['gene'] = gene
        kwargs['disable_reads_filter'] = ViewConfig().disable_reads

        return render_template(summary_template, **kwargs)


def find_exon_number(exons, ref_exon, strand):
    exons = filter(lambda e: -1 not in [e['start'], e['end']], exons)
    exons = list(exons)

    for idx, exon in enumerate(exons):

        if (exon['start'], exon['end']) == ref_exon:
            if strand == '-':
                return len(exons) - idx
            else:
                return idx + 1
    return 'unk'


def filter_gene_for_lsv(exons, junctions, introns, lsv_junctions):
    out_exons = []

    out_junctions = [x for x in junctions if [x['start'], x['end']] in lsv_junctions.tolist()]

voila/rna_voila/view/templates/base.html
{% set vconf = config["VOILA_CONFIG"] %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
<link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/lib/pure-min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/lib/jquery.dataTables.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/lsv.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/copy_lsv.css') }}">
    {% block style %}{% endblock %}

</head>
<body>
<div class="modal">
    <div class="modal-content">
        <span class="modal-close">&times;</span>
        <p> Copy LSV text below:</p>
        <input type="text" title="copy-lsv" placeholder="Getting LSV text...">
    </div>
</div>

{% block header %}{% endblock %}
{% block content %}{% endblock %}
{% block footer %}{% endblock %}

</body>
<script>
    const base_url = '{{ config["EXT_URL_PREFIX"] }}';
    const longread_enabled = {{ "true" if vconf["long_read_file"] else "false" }};
    const combined_colors = {
        'sla': '#332288',
        'sl': '#44AA99',
        'l': '#EA07C5',
        'la': '#DDCC77',
        's': '#117733',
        'sa': '#882255',
        'ao': '#808080'
    };
</script>
<script src="{{ url_for('static', filename='js/lib/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/lib/jquery.dataTables.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/lib/d3.v5.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/lib/d3-beeswarm.js') }}"></script>
<script src="{{ url_for('static', filename='js/lib/clipboard.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/utils.js') }}"></script>
<script src="{{ url_for('static', filename='js/ajax.js') }}"></script>
<script src="{{ url_for('static', filename='js/splicegraphs.js') }}"></script>
<script src="{{ url_for('static', filename='js/splicegraphtools.js') }}"></script>
<script src="{{ url_for('static', filename='js/plotOptions.js') }}"></script>
<script src="{{ url_for('static', filename='js/table.js') }}"></script>
<script src="{{ url_for('static', filename='js/violin.js') }}"></script>
<script src="{{ url_for('static', filename='js/heatmap.js') }}"></script>
<script src="{{ url_for('static', filename='js/colors.js') }}"></script>
<script src="{{ url_for('static', filename='js/lsv.js') }}"></script>
<script src="{{ url_for('static', filename='js/copy_lsv.js') }}"></script>
<script src="{{ url_for('static', filename='js/common.js') }}"></script>

{% block script %}{% endblock %}
</html>

voila/rna_voila/view/templates/dpsi_index.html
{% extends 'base_index.html' %}

{% block script %}
    <script>
        const view_type = 'dpsi';

        new MutationObserver(mutations => {
            mutations.forEach(m => m.addedNodes
                .forEach(n => {
                    const tds = n.querySelectorAll('td:not(.dataTables_empty)');

                    if (!tds.length)
                        return;

                    const lsv_id = tds[1].textContent;

                    json_ajax('{{ url_for("main.lsv_data") }}/' + encodeURIComponent(lsv_id))
                        .then(lsv_data => {
                            const lsv = new Lsv(lsv_data);
                            const violin = new Violin(lsv_data.lsv);
                            n.querySelectorAll('.excl-incl-rect')
                                .forEach(s => {
                                    lsv.draw_delta_lsv_compact_svg(s);
                                });

                            n.querySelectorAll('.dpsi-violin')
                                .forEach(s => {
                                    $(s).hide();
                                    violin.deltapsi(s);
                                });

                            n.querySelectorAll('.lsv-cartoon')
                                .forEach(s => lsv.cartoon(s));

                        });


                    copy_lsv_modal(n, '{{ url_for("main.copy_lsv") }}/' + encodeURIComponent(lsv_id))
                })
            );
        })
            .observe(document.querySelector('#results tbody'), {
                childList: true,
            });

        const form_to_json = (json_data) => {
            $('.lsv-filters')
                .serializeArray()
                .map(d => {
                    json_data[`lsv_filter[${d.name}]`] = d.value
                });
            $('.dpsi-filters')
                .serializeArray()
                .map(d => {
                    json_data[`dpsi_filter[${d.name}]`] = d.value
                });
        };


        const $results = $('#results').DataTable({
            processing: true,
            serverSide: true,
            autoWidth: false,
            lengthMenu: [[10, 25, 50, 100, 1000], [10, 25, 50, 100, 1000]],
            ajax: {
                url: '{{ url_for("main.index_table") }}',
                type: 'POST',
                data: json_data => form_to_json(json_data)
            },
            columnDefs: [
                {
                    targets: 0,
                    render: (data, _, cols) => {
                        const element = document.createElement('a');
                        const lsv_id = cols[1];
                        // we can move onto a more complicated query string writer / parser when the need arises
                        element.href = data[0] + `?absEdPSI_Threshold=${$('#dpsi_threshold').val()}&lsv_id=${lsv_id}`;
                        element.target = '_blank';
                        element.rel = "noopener noreferrer";
                        element.textContent = data[1] + ' ⎆';
                        element.classList.add('pure-button');
                        element.classList.add('pure-button-primary');
                        element.title = `Analyze gene ${data[1]} in depth`;
                        element.style = "font-size: 150%; background-color: #009be7;";
                        return element.outerHTML
                    }
                },
                {
                    targets: 2,
                    sortable: false,
                    render: data => {
                        const element = document.createElement('canvas');
                        element.setAttribute('width', '200');
                        element.setAttribute('height', '80');
                        element.classList.add('lsv-cartoon');
                        element.dataset.lsvType = data;
                        return element.outerHTML
                    }
                },
                {
                    targets: 3,
                    render: () => {
                        const excl_incl = document.createElement('svg');
                        excl_incl.classList.add('excl-incl-rect');
                        excl_incl.setAttribute('width', '0');
                        excl_incl.setAttribute('height', '0');

                        const dpsi_violin = document.createElement('svg');
                        dpsi_violin.classList.add('dpsi-violin');
                        dpsi_violin.setAttribute('width', '0');
                        dpsi_violin.setAttribute('height', '0');

                        return excl_incl.outerHTML + dpsi_violin.outerHTML;
                    }
                },
                {
                    targets: 4,
                    sortable: false,
                    render: data => {
                        const copy_lsv = document.createElement('button');
                        copy_lsv.textContent = 'Copy LSV';
                        copy_lsv.classList.add('pure-button', 'copy-lsv');

                        const ucsc_a = document.createElement('a');
                        ucsc_a.href = data;
                        ucsc_a.target = '_blank';
                        ucsc_a.rel = 'noopener noreferrer';
                        const ucsc_img = document.createElement('img');
                        ucsc_img.src = '{{ url_for('static', filename="img/ucsc.png") }}';
                        ucsc_a.appendChild(ucsc_img);

                        return copy_lsv.outerHTML + ucsc_a.outerHTML
                    }
                }
            ]
        });

        let to;
        const reload_table = () => {
            clearTimeout(to);
            to = setTimeout(() => {
                $results.ajax.reload()
            }, 400);
        };


        document.querySelector('.lsv-filters').onchange = reload_table;
        document.querySelector('.dpsi-filters').oninput = reload_table;

        function download(filename, text) {
            var element = document.createElement('a');
            element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
            element.setAttribute('download', filename);

            element.style.display = 'none';
            document.body.appendChild(element);

            element.click();

            document.body.removeChild(element);
        }

        document.querySelector('.download-lsvs').onclick = (event) => {
            event.preventDefault();

            const search = document.querySelector('.lsv-container input[type=search]');
            const form_data = {};
            form_to_json(form_data);
            form_data['search[value]'] = search.value;

            send_form_ajax('{{ url_for("main.download_lsvs") }}', $.param(form_data))
                .then(data => download('lsvs.txt', data));
        };

        document.querySelector('.download-genes').onclick = (event) => {
            event.preventDefault();

            const search = document.querySelector('.lsv-container input[type=search]');
            const form_data = {};
            form_to_json(form_data);
            form_data['search[value]'] = search.value;

            send_form_ajax('{{ url_for("main.download_genes") }}', $.param(form_data))
                .then(data => download('genes.txt', data));
        };

        $('#results tbody')
            .on('click', '.excl-incl-rect, .dpsi-violin', event => {
                const parent = event.target.closest('td');
                const excl_incl = parent.querySelector('.excl-incl-rect');
                const violin = parent.querySelector('.dpsi-violin');
                $(violin).toggle();
                $(excl_incl).toggle();
            });

        function outputUpdate(val) {
            document.querySelector('#selected_confidence_threshold').value = val;
        }

    </script>
{% endblock %}

{% block filters %}
    <form class="lsv-filters pure-form pure-form-aligned">
        <fieldset>
            <legend>LSV Filters</legend>
            <div class="pure-g">
                {% for field in form %}
                    {% if field.type != 'CSRFTokenField' %}
                        <div class="pure-u-1-3">
                            {{ field }}
                            {{ field.label }}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </fieldset>
    </form>

    <hr>

    <form class="dpsi-filters pure-form pure-form-aligned">
        <fieldset>
            <div class="pure-g">
                <div class="pure-u-1-4">
                    {{ dpsi_form.dpsi_threshold.label }}
                    {{ dpsi_form.dpsi_threshold }}
                </div>

                <div class="pure-u-1-4">
                    {{ dpsi_form.confidence_threshold.label }}
                    {{ dpsi_form.confidence_threshold(min=0.0, max=1.0, step=0.1, oninput="outputUpdate(value)") }}
                    <output for="confidence_threshold" id="selected_confidence_threshold">{{ dpsi_form.confidence_threshold.data }}</output>
                </div>
                <div class="pure-u-1-4">
                    <button type="submit" class="download-lsvs pure-button pure-button-primary">Download LSVs
                    </button>
                </div>
                <div class="pure-u-1-4">
                    <button type="submit" class="download-genes pure-button pure-button-primary">Download Genes
                    </button>
                </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

{% block index_table %}
    <div>
        <table id="results" class="pure-table">
            <thead>
            <tr>
                <th>Gene Name</th>
                <th>LSV ID</th>
                <th>LSV Type</th>
                <th>∆Ψ per Junction</th>
                <th>Links</th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
{% endblock %}

voila/rna_voila/view/templates/multipsi_index.html
{% extends 'base_index.html' %}

{% block script %}
    <script>

        const view_type = 'multipsi';

        new MutationObserver(mutations => {
            mutations.forEach(m => m.addedNodes
                .forEach(n => {
                    const tds = n.querySelectorAll('td:not(.dataTables_empty)');

                    if (!tds.length)
                        return;

                    const lsv_id = tds[1].textContent;


                    json_ajax('{{ url_for("main.lsv_data") }}/' + encodeURIComponent(lsv_id)).then(lsv_data => {

                        const lsv = new Lsv(lsv_data);
                        lsv.cartoon(n.querySelector('.lsv-cartoon'));

                    });

                    copy_lsv_modal(n, '{{ url_for("main.copy_lsv") }}/' + encodeURIComponent(lsv_id))
                })
            );
        })
            .observe(document.querySelector('#results tbody'), {
                childList: true,
            });

        const form_to_json = (json_data) => {
            $('.lsv-filters')
                .serializeArray()
                .map(d => {
                    json_data[`lsv_filter[${d.name}]`] = d.value
                });
        };

        const $results = $('#results').DataTable({
            processing: true,
            serverSide: true,
            autoWidth: false,
            lengthMenu: [[10, 25, 50, 100, 1000], [10, 25, 50, 100, 1000]],
            ajax: {
                url: '{{ url_for("main.index_table") }}',
                type: 'POST',
                data: json_data => form_to_json(json_data)
            },
            columnDefs: [
                {
                    targets: 0,
                    render: (data, _, cols) => {
                        const element = document.createElement('a');
                        const lsv_id = cols[1];
                        element.href = data.href + `?lsv_id=${lsv_id}`;
                        element.target = '_blank';
                        element.rel = "noopener noreferrer";
                        element.textContent = data.gene_name + ' ⎆';
                        element.classList.add('pure-button');
                        element.classList.add('pure-button-primary');
                        element.title = `Analyze gene ${data.gene_name} in depth`;
                        element.style = "font-size: 150%; background-color: #009be7;";
                        return element.outerHTML
                    }
                },
                {
                    targets: 2,
                    sortable: false,
                    render: data => {
                        const element = document.createElement('canvas');
                        element.setAttribute('width', '200');
                        element.setAttribute('height', '80');
                        element.classList.add('lsv-cartoon');
                        element.dataset.lsvType = data;
                        return element.outerHTML
                    }
                },
                {
                    targets: 3,
                    sortable: false,
                    render: data => {
                        const copy_lsv = document.createElement('button');
                        copy_lsv.textContent = 'Copy LSV';
                        copy_lsv.classList.add('pure-button', 'copy-lsv');

                        const ucsc_a = document.createElement('a');
                        ucsc_a.href = data;
                        ucsc_a.target = '_blank';
                        ucsc_a.rel = 'noopener noreferrer';
                        const ucsc_img = document.createElement('img');
                        ucsc_img.src = '{{ url_for('static', filename="img/ucsc.png") }}';
                        ucsc_a.appendChild(ucsc_img);

                        return copy_lsv.outerHTML + ucsc_a.outerHTML
                    }
                }
            ]
        });

        let to;
        const reload_table = () => {
            clearTimeout(to);
            to = setTimeout(() => {
                $results.ajax.reload()
            }, 400);
        };


        function download(filename, text) {
            var element = document.createElement('a');
            element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
            element.setAttribute('download', filename);

            element.style.display = 'none';
            document.body.appendChild(element);

            element.click();

            document.body.removeChild(element);
        }

        document.querySelector('.lsv-filters').onchange = reload_table;


        document.querySelector('.download-lsvs').onclick = (event) => {
            event.preventDefault();

            const search = document.querySelector('.lsv-container input[type=search]');
            const form_data = {};
            form_to_json(form_data);
            form_data['search[value]'] = search.value;

            send_form_ajax('{{ url_for("main.download_lsvs") }}', $.param(form_data))
                .then(data => download('lsvs.txt', data));
        };

        document.querySelector('.download-genes').onclick = (event) => {
            event.preventDefault();

            const search = document.querySelector('.lsv-container input[type=search]');
            const form_data = {};
            form_to_json(form_data);
            form_data['search[value]'] = search.value;

            send_form_ajax('{{ url_for("main.download_genes") }}', $.param(form_data))
                .then(data => download('genes.txt', data));
        };

        $('#results tbody')
            .on('click', '.psi-violin-plot, .lsv-single-compact-percentiles', event => {
                const parent = event.target.closest('td');
                const violin = parent.querySelector('.psi-violin-plot');
                const compact = parent.querySelector('.lsv-single-compact-percentiles');
                $(violin).toggle();
                $(compact).toggle();
            })

    </script>
{% endblock %}

{% block filters %}
    <form class="lsv-filters pure-form pure-form-aligned">
        <fieldset>
            <legend>LSV Filters</legend>
            <div class="pure-g">
                {% for field in form %}
                    {% if field.type != 'CSRFTokenField' %}
                        <div class="pure-u-1-3">
                            {{ field }}
                            {{ field.label }}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </fieldset>
    </form>

    <hr>

    <form class="psi-filters pure-form pure-form-aligned">
        <fieldset>
            <div class="pure-g">
                <div class="pure-u-1-4">
                    <button type="submit" class="download-lsvs pure-button pure-button-primary">Download LSVs
                    </button>
                </div>

                <div class="pure-u-1-4">
                    <button type="submit" class="download-genes pure-button pure-button-primary">Download Genes
                    </button>
                </div>

            </div>
        </fieldset>
    </form>
{% endblock %}

{% block index_table %}
    <div class="lsv-container">
        <div>
            <table id="results" class="pure-table">
                <thead>
                <tr>
                    <th>Gene Name</th>
                    <th>LSV ID</th>
                    <th>LSV Type</th>
                    <th>Links</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}